version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_catalog
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
